/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AccommodationSearch(props) {
  return (
    <section>
      <h1>Find and book unique accommodations</h1>
      <p>Your next great getaway starts here.</p>
      <form>
        <div>
          <label htmlFor="location">Location</label>
          <input type="text" id="location" placeholder="Location" />
        </div>
        <div>
          <button className="bg-black bg-opacity-0 border-black border-opacity-0 max-md:bg-rose-500 max-md:border-white">
            Search
          </button>
        </div>
      </form>
      <img
        loading="lazy"
        alt=""
        srcSet="..."
        className="object-cover object-center w-full"
      />
    </section>
  );
}

export default AccommodationSearch;
